language: ruby
sudo: false
cache: bundler
script: 'script/ci'
rvm:
  - 2.2.5
  - 2.3.1
  - ruby-head
  - jruby-9.0.5.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
